---
# tasks file for jupyterhub-apb
#
- name: copy files to /tmp
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_items:
    - "jupyterhub-templates.json"
    - "notebook-images.json"
    - "jupyter-images.json"

- name: create buildconfigs, templates, and imagestreams
  openshift_raw:
    state: "{{ state }}"
    definition: "{{ lookup('file', item.name) | from_json }}"
  loop:
    - name: /tmp/jupyterhub-templates.json
    - name: /tmp/notebook-images.json
    - name: /tmp/jupyter-images.json

- name: Create jupyterhub deployment
  shell: oc new-app --template jupyterhub-deployer -n {{ namespace }}
