---
# tasks file for jupyterhub-apb

- name: Create jupyterhub objects
  openshift_raw:
    state: present
    definition: "{{ lookup('template', item) }}"
  with_items:
    - jupyterhub-buildconfig.json.j2
    - jupyterhub-builder-template.json.j2
    - jupyterhub-deployer-template.json.j2
    - jupyterhub-imagestream.json.j2
    - jupyterhub-quickstart-template.json.j2

- name: Create notebook objects
  openshift_raw:
    state: present
    definition: "{{ lookup('template', item) }}"
  with_items:
    - minimal-notebook-buildconfig.json.j2
    - minimal-notebook-imagestream.json.j2
    - scipy-notebook-buildconfig.json.j2
    - scipy-notebook-imagestream.json.j2
    - tensorflow-notebook-buildconfig.json.j2
    - tensorflow-notebook-imagestream.json.j2

